language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ivaan7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ivaan7/react-test npm test

after_success:
  - docker build -t ivaan7/multi-client ./client
  - docker build -t ivaan7/multi-nginx ./nginx
  - docker build -t ivaan7/multi-server ./server
  - docker build -t ivaan7/multi-worker ./worker
  #Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push image to docker hub
  - docker push ivaan7/multi-client
  - docker push ivaan7/multi-nginx
  - docker push ivaan7/multi-server
  - docker push ivaan7/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-804563431245
  bucket_path: docker-multi-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

